name: Deploy to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/azure/**'
      - 'examples/blob-deploy/**'
      - '.github/workflows/deploy-azure.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/azure/**'
      - 'examples/blob-deploy/**'
  workflow_dispatch:

# Required permissions for OIDC
permissions:
  id-token: write   # Required for requesting JWT
  contents: read    # Required for actions/checkout

env:
  AZURE_REGION: eastus
  # Replace with your values after deploying terraform/azure
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        working-directory: terraform/azure
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: terraform/azure
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: terraform/azure
        run: terraform validate

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: validate-terraform
    # Only deploy on push to main, not PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Azure identity
        run: |
          echo "Verifying Azure credentials..."
          az account show
          echo "Successfully authenticated to Azure using OIDC!"

      - name: Get Azure account information
        run: |
          echo "Subscription ID: $(az account show --query id -o tsv)"
          echo "Subscription Name: $(az account show --query name -o tsv)"
          echo "Tenant ID: $(az account show --query tenantId -o tsv)"

      - name: List resource groups (example)
        run: |
          echo "Listing resource groups to verify permissions..."
          az group list --output table || echo "No resource groups found or insufficient permissions"

  test-deployment:
    name: Test Blob Storage Deployment
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Create test file
        run: |
          echo "Test file created by GitHub Actions using OIDC" > test-file.txt
          echo "Timestamp: $(date)" >> test-file.txt
          echo "Run ID: ${{ github.run_id }}" >> test-file.txt

      - name: Test Blob Storage upload (if storage account exists)
        continue-on-error: true
        run: |
          STORAGE_ACCOUNT="keylesstest$(az account show --query id -o tsv | cut -c1-8)"
          CONTAINER_NAME="github-actions-test"
          echo "Testing upload to storage account: $STORAGE_ACCOUNT"

          # Check if storage account exists
          if az storage account show --name "$STORAGE_ACCOUNT" 2>/dev/null; then
            # Get storage account key
            ACCOUNT_KEY=$(az storage account keys list --account-name "$STORAGE_ACCOUNT" --query '[0].value' -o tsv)

            # Create container if it doesn't exist
            az storage container create \
              --name "$CONTAINER_NAME" \
              --account-name "$STORAGE_ACCOUNT" \
              --account-key "$ACCOUNT_KEY" \
              --fail-on-exist false

            # Upload test file
            az storage blob upload \
              --account-name "$STORAGE_ACCOUNT" \
              --account-key "$ACCOUNT_KEY" \
              --container-name "$CONTAINER_NAME" \
              --name "github-actions-test.txt" \
              --file test-file.txt \
              --overwrite

            echo "Successfully uploaded test file to Azure Blob Storage"
          else
            echo "Test storage account does not exist. Skipping upload test."
            echo "To enable this test, create a storage account named: $STORAGE_ACCOUNT"
          fi

      - name: Cleanup
        run: rm -f test-file.txt
